services:
  frontend:
    build:
      context: .
  proxy:
    image: nginx:1.17.4
    volumes:
      - ./nginx/default.conf:/tmp/default.conf.template
    command: ["/bin/bash", "-c", "envsubst < /tmp/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
    environment:
      APP_SERVER: 'http://frontend:8080'
      API_SERVER: '${API_SERVER:-http://host.docker.internal:8080}'
    ports:
      - "80:80"
